//===================================================================================
// Microsoft patterns & practices
// Composite Application Guidance for Windows Presentation Foundation and Silverlight
//===================================================================================
// Copyright (c) Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===================================================================================
// The example companies, organizations, products, domain names,
// e-mail addresses, logos, people, places, and events depicted
// herein are fictitious.  No association with any real company,
// organization, product, domain name, email address, logo, person,
// places, or events is intended or should be inferred.
//===================================================================================
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockTraderRI.Tests.AcceptanceTest.TestData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControlIdentifiers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControlIdentifiers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StockTraderRI.Tests.AcceptanceTest.TestData.ControlIdentifiers", typeof(ControlIdentifiers).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsBuyButton.
        /// </summary>
        internal static string ActionsBuyButton_Silverlight {
            get {
                return ResourceManager.GetString("ActionsBuyButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsBuyButton.
        /// </summary>
        internal static string ActionsBuyButton_Wpf {
            get {
                return ResourceManager.GetString("ActionsBuyButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsRemoveButton.
        /// </summary>
        internal static string ActionsRemoveButton_Silverlight {
            get {
                return ResourceManager.GetString("ActionsRemoveButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsRemoveButton.
        /// </summary>
        internal static string ActionsRemoveButton_Wpf {
            get {
                return ResourceManager.GetString("ActionsRemoveButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsSellButton.
        /// </summary>
        internal static string ActionsSellButton_Silverlight {
            get {
                return ResourceManager.GetString("ActionsSellButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionsSellButton.
        /// </summary>
        internal static string ActionsSellButton_Wpf {
            get {
                return ResourceManager.GetString("ActionsSellButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToWatchListButton.
        /// </summary>
        internal static string AddToWatchListButton_Silverlight {
            get {
                return ResourceManager.GetString("AddToWatchListButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddToWatchListButton.
        /// </summary>
        internal static string AddToWatchListButton_Wpf {
            get {
                return ResourceManager.GetString("AddToWatchListButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyRadioButton.
        /// </summary>
        internal static string BuyRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("BuyRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BuyRadioButton.
        /// </summary>
        internal static string BuyRadioButton_Wpf {
            get {
                return ResourceManager.GetString("BuyRadioButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Silverlight {
            get {
                return ResourceManager.GetString("Cancel_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_Wpf {
            get {
                return ResourceManager.GetString("Cancel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        internal static string CancelAll_Silverlight {
            get {
                return ResourceManager.GetString("CancelAll_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel All.
        /// </summary>
        internal static string CancelAll_Wpf {
            get {
                return ResourceManager.GetString("CancelAll_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelAllButton.
        /// </summary>
        internal static string CancelAllButton_Silverlight {
            get {
                return ResourceManager.GetString("CancelAllButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelAllButton.
        /// </summary>
        internal static string CancelAllButton_Wpf {
            get {
                return ResourceManager.GetString("CancelAllButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButton.
        /// </summary>
        internal static string CancelButton_Silverlight {
            get {
                return ResourceManager.GetString("CancelButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CancelButton.
        /// </summary>
        internal static string CancelButton_Wpf {
            get {
                return ResourceManager.GetString("CancelButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpanderButton.
        /// </summary>
        internal static string ExpanderButton_Silverlight {
            get {
                return ResourceManager.GetString("ExpanderButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalDataChart.
        /// </summary>
        internal static string HistoricalDataChart_Silverlight {
            get {
                return ResourceManager.GetString("HistoricalDataChart_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalDataChart.
        /// </summary>
        internal static string HistoricalDataChart_Wpf {
            get {
                return ResourceManager.GetString("HistoricalDataChart_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalDataTextBlock.
        /// </summary>
        internal static string HistoricalDataTextBlock_Silverlight {
            get {
                return ResourceManager.GetString("HistoricalDataTextBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HistoricalDataTextBlock.
        /// </summary>
        internal static string HistoricalDataTextBlock_Wpf {
            get {
                return ResourceManager.GetString("HistoricalDataTextBlock_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsArticleText.
        /// </summary>
        internal static string NewsArticleText_Silverlight {
            get {
                return ResourceManager.GetString("NewsArticleText_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NewsArticleText.
        /// </summary>
        internal static string NewsArticleText_Wpf {
            get {
                return ResourceManager.GetString("NewsArticleText_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickCancel.
        /// </summary>
        internal static string OrderCommandCancel_Silverlight {
            get {
                return ResourceManager.GetString("OrderCommandCancel_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickCancel.
        /// </summary>
        internal static string OrderCommandCancel_Wpf {
            get {
                return ResourceManager.GetString("OrderCommandCancel_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickCancelAllButton.
        /// </summary>
        internal static string OrderCommandCancelAllButton_Silverlight {
            get {
                return ResourceManager.GetString("OrderCommandCancelAllButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickCancelAllButton.
        /// </summary>
        internal static string OrderCommandCancelAllButton_Wpf {
            get {
                return ResourceManager.GetString("OrderCommandCancelAllButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickSubmit.
        /// </summary>
        internal static string OrderCommandSubmit_Silverlight {
            get {
                return ResourceManager.GetString("OrderCommandSubmit_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickSubmit.
        /// </summary>
        internal static string OrderCommandSubmit_Wpf {
            get {
                return ResourceManager.GetString("OrderCommandSubmit_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickSubmitAllButton.
        /// </summary>
        internal static string OrderCommandSubmitAllButton_Silverlight {
            get {
                return ResourceManager.GetString("OrderCommandSubmitAllButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderClickSubmitAllButton.
        /// </summary>
        internal static string OrderCommandSubmitAllButton_Wpf {
            get {
                return ResourceManager.GetString("OrderCommandSubmitAllButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTypeComboBox.
        /// </summary>
        internal static string OrderTypeComboBox_Silverlight {
            get {
                return ResourceManager.GetString("OrderTypeComboBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderTypeComboBox.
        /// </summary>
        internal static string OrderTypeComboBox_Wpf {
            get {
                return ResourceManager.GetString("OrderTypeComboBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PieChartTextBlock.
        /// </summary>
        internal static string PieChartTextBlock_Silverlight {
            get {
                return ResourceManager.GetString("PieChartTextBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PieChartTextBlock.
        /// </summary>
        internal static string PieChartTextBlock_Wpf {
            get {
                return ResourceManager.GetString("PieChartTextBlock_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionBuySellTab.
        /// </summary>
        internal static string PositionBuySellTab_Silverlight {
            get {
                return ResourceManager.GetString("PositionBuySellTab_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionBuySellTab.
        /// </summary>
        internal static string PositionBuySellTab_Wpf {
            get {
                return ResourceManager.GetString("PositionBuySellTab_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionSummaryGrid.
        /// </summary>
        internal static string PositionSummaryGrid_Silverlight {
            get {
                return ResourceManager.GetString("PositionSummaryGrid_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionSummaryGrid.
        /// </summary>
        internal static string PositionSummaryGrid_Wpf {
            get {
                return ResourceManager.GetString("PositionSummaryGrid_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionSummaryTab.
        /// </summary>
        internal static string PositionSummaryTab_Silverlight {
            get {
                return ResourceManager.GetString("PositionSummaryTab_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PositionSummaryTab.
        /// </summary>
        internal static string PositionSummaryTab_Wpf {
            get {
                return ResourceManager.GetString("PositionSummaryTab_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLimitTextBox.
        /// </summary>
        internal static string PriceLimitTextBox_Silverlight {
            get {
                return ResourceManager.GetString("PriceLimitTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceLimitTextBox.
        /// </summary>
        internal static string PriceLimitTextBox_Wpf {
            get {
                return ResourceManager.GetString("PriceLimitTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellRadioButton.
        /// </summary>
        internal static string SellRadioButton_Silverlight {
            get {
                return ResourceManager.GetString("SellRadioButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SellRadioButton.
        /// </summary>
        internal static string SellRadioButton_Wpf {
            get {
                return ResourceManager.GetString("SellRadioButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharesTextBox.
        /// </summary>
        internal static string SharesTextBox_Silverlight {
            get {
                return ResourceManager.GetString("SharesTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SharesTextBox.
        /// </summary>
        internal static string SharesTextBox_Wpf {
            get {
                return ResourceManager.GetString("SharesTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StockTraderRI.
        /// </summary>
        internal static string SilverlightAppTitle {
            get {
                return ResourceManager.GetString("SilverlightAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_Silverlight {
            get {
                return ResourceManager.GetString("Submit_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit_Wpf {
            get {
                return ResourceManager.GetString("Submit_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit All.
        /// </summary>
        internal static string SubmitAll_Silverlight {
            get {
                return ResourceManager.GetString("SubmitAll_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit All.
        /// </summary>
        internal static string SubmitAll_Wpf {
            get {
                return ResourceManager.GetString("SubmitAll_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitAllButton.
        /// </summary>
        internal static string SubmitAllButton_Silverlight {
            get {
                return ResourceManager.GetString("SubmitAllButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitAllButton.
        /// </summary>
        internal static string SubmitAllButton_Wpf {
            get {
                return ResourceManager.GetString("SubmitAllButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButton.
        /// </summary>
        internal static string SubmitButton_Silverlight {
            get {
                return ResourceManager.GetString("SubmitButton_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SubmitButton.
        /// </summary>
        internal static string SubmitButton_Wpf {
            get {
                return ResourceManager.GetString("SubmitButton_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbolTextBox.
        /// </summary>
        internal static string SymbolTextBox_Silverlight {
            get {
                return ResourceManager.GetString("SymbolTextBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbolTextBox.
        /// </summary>
        internal static string SymbolTextBox_Wpf {
            get {
                return ResourceManager.GetString("SymbolTextBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermComboBox.
        /// </summary>
        internal static string TermComboBox_Silverlight {
            get {
                return ResourceManager.GetString("TermComboBox_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TermComboBox.
        /// </summary>
        internal static string TermComboBox_Wpf {
            get {
                return ResourceManager.GetString("TermComboBox_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxBlock.
        /// </summary>
        internal static string TextBoxBlock_Silverlight {
            get {
                return ResourceManager.GetString("TextBoxBlock_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TextBoxBlock.
        /// </summary>
        internal static string TextBoxBlock_Wpf {
            get {
                return ResourceManager.GetString("TextBoxBlock_Wpf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchListGrid.
        /// </summary>
        internal static string WatchListGrid_Silverlight {
            get {
                return ResourceManager.GetString("WatchListGrid_Silverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WatchListGrid.
        /// </summary>
        internal static string WatchListGrid_Wpf {
            get {
                return ResourceManager.GetString("WatchListGrid_Wpf", resourceCulture);
            }
        }
    }
}
